// Generated by `zig build gen-types`. Do not edit manually.
import type { CommandArgs, CommandMap, CommandReturn } from "../types-generated/commands.generated";
import { invoke } from "./invoke";

export type CommandClient = {
  ping: (input: { message: string; }) => Promise<CommandReturn<'ping'>>;
  sum: (a: number, b: number) => Promise<CommandReturn<'sum'>>;
  echo: (input: { text: string; }) => Promise<CommandReturn<'echo'>>;
  health: () => Promise<CommandReturn<'health'>>;
  multiplication: (a: number, b: number) => Promise<CommandReturn<'multiplication'>>;
  soma: (input: { input_a: number; input_b: number; }) => Promise<CommandReturn<'soma'>>;
  multiply: (input: { left: number; right: number; }) => Promise<CommandReturn<'multiply'>>;
  sub: (a: number, b: number) => Promise<CommandReturn<'sub'>>;
  getLastName: (lastName: string) => Promise<CommandReturn<'getLastName'>>;
  getFullName: (lastName: string) => Promise<CommandReturn<'getFullName'>>;
};

export const commands: CommandClient = {
  ping: async (input: { message: string; }) => invoke('ping', input),
  sum: async (a: number, b: number) => invoke('sum', a, b),
  echo: async (input: { text: string; }) => invoke('echo', input),
  health: async () => invoke('health'),
  multiplication: async (a: number, b: number) => invoke('multiplication', a, b),
  soma: async (input: { input_a: number; input_b: number; }) => invoke('soma', input),
  multiply: async (input: { left: number; right: number; }) => invoke('multiply', input),
  sub: async (a: number, b: number) => invoke('sub', a, b),
  getLastName: async (lastName: string) => invoke('getLastName', lastName),
  getFullName: async (lastName: string) => invoke('getFullName', lastName),
};
