// Generated by `zig build gen-types`. Do not edit manually.
import type { CommandReturn } from "../types-generated/commands.generated";
import { invoke } from "./invoke";

export type CommandClient = {
  ping: (input: { message: string; }) => Promise<CommandReturn<'ping'>>;
  sum: (a: number, b: number) => Promise<CommandReturn<'sum'>>;
  echo: (input: { text: string; }) => Promise<CommandReturn<'echo'>>;
  health: () => Promise<CommandReturn<'health'>>;
  multiplication: (a: number, b: number) => Promise<CommandReturn<'multiplication'>>;
  soma: (input: { input_a: number; input_b: number; }) => Promise<CommandReturn<'soma'>>;
  multiply: (input: { left: number; right: number; }) => Promise<CommandReturn<'multiply'>>;
  sub: (a: number, b: number) => Promise<CommandReturn<'sub'>>;
  getLastName: (lastName: string) => Promise<CommandReturn<'getLastName'>>;
  getFullName: (lastName: string) => Promise<CommandReturn<'getFullName'>>;
  get_ui_bootstrap: (input: { window_kind: 'minibar' | 'control_panel'; }) => Promise<CommandReturn<'get_ui_bootstrap'>>;
  log_client_event: (input: { level: 'DEBUG' | 'INFO' | 'WARN' | 'ERROR'; trace_id: string; session_id?: string | null; module: string; event: string; message: string; error?: string | null; stack?: string | null; metadata_json?: string | null; }) => Promise<CommandReturn<'log_client_event'>>;
  open_control_panel: () => Promise<CommandReturn<'open_control_panel'>>;
};

export const commands: CommandClient = {
  ping: async (input: { message: string; }) => invoke('ping', input),
  sum: async (a: number, b: number) => invoke('sum', a, b),
  echo: async (input: { text: string; }) => invoke('echo', input),
  health: async () => invoke('health'),
  multiplication: async (a: number, b: number) => invoke('multiplication', a, b),
  soma: async (input: { input_a: number; input_b: number; }) => invoke('soma', input),
  multiply: async (input: { left: number; right: number; }) => invoke('multiply', input),
  sub: async (a: number, b: number) => invoke('sub', a, b),
  getLastName: async (lastName: string) => invoke('getLastName', lastName),
  getFullName: async (lastName: string) => invoke('getFullName', lastName),
  get_ui_bootstrap: async (input: { window_kind: 'minibar' | 'control_panel'; }) => invoke('get_ui_bootstrap', input),
  log_client_event: async (input: { level: 'DEBUG' | 'INFO' | 'WARN' | 'ERROR'; trace_id: string; session_id?: string | null; module: string; event: string; message: string; error?: string | null; stack?: string | null; metadata_json?: string | null; }) => invoke('log_client_event', input),
  open_control_panel: async () => invoke('open_control_panel'),
};
