// Generated by `zig build gen-types`. Do not edit manually.
/// <reference path="../types-generated/global.generated.d.ts" />

import type {
  CommandMap,
  InvokeTuple,
} from "../types-generated/commands.generated";

export async function invoke<T extends keyof CommandMap>(
  command: T,
  ...args: CommandMap[T]["args"]
): Promise<InvokeTuple<T>> {
  return window.invoke(command, ...args);
}
