// Generated by `zig build gen-types`. Do not edit manually.
import type { CommandArgs, CommandMap, CommandReturn } from './commands.generated';

declare global {
  interface Window {
    __mini_invoke__(command: 'ping', input: { message: string; }): Promise<CommandReturn<'ping'>>;
    __mini_invoke__(command: 'sum', a: number, b: number): Promise<CommandReturn<'sum'>>;
    __mini_invoke__(command: 'echo', input: { text: string; }): Promise<CommandReturn<'echo'>>;
    __mini_invoke__(command: 'health'): Promise<CommandReturn<'health'>>;
    __mini_invoke__(command: 'multiplication', a: number, b: number): Promise<CommandReturn<'multiplication'>>;
    __mini_invoke__(command: 'soma', input: { input_a: number; input_b: number; }): Promise<CommandReturn<'soma'>>;
    __mini_invoke__(command: 'multiply', input: { left: number; right: number; }): Promise<CommandReturn<'multiply'>>;
    __mini_invoke__(command: 'sub', a: number, b: number): Promise<CommandReturn<'sub'>>;
    __mini_invoke__(command: 'getLastName', lastName: string): Promise<CommandReturn<'getLastName'>>;
    __mini_invoke__(command: 'getFullName', lastName: string): Promise<CommandReturn<'getFullName'>>;
    __mini_invoke__<T extends keyof CommandMap>(
      command: T,
      ...args: CommandArgs<T>
    ): Promise<CommandReturn<T>>;
  }
}

export {};
