// Generated by `zig build gen-types`. Do not edit manually.
export type CommandMap = {
  'ping': { args: [{ message: string; }]; result: { command: string; echoed: string; timestamp_ms: number; } };
  'sum': { args: [number, number]; result: { command: string; result: number; } };
  'echo': { args: [{ text: string; }]; result: { command: string; value: string; length: number; } };
  'health': { args: []; result: { command: string; ok: boolean; service: string; } };
  'multiplication': { args: [number, number]; result: { command: string; result: number; } };
  'soma': { args: [{ input_a: number; input_b: number; }]; result: { command: string; result: number; } };
  'multiply': { args: [{ left: number; right: number; }]; result: { command: string; result: number; } };
  'sub': { args: [number, number]; result: number };
  'getLastName': { args: [string]; result: string };
  'getFullName': { args: [string]; result: { text: string; } | { error: { message: string; }; } };
  'get_ui_bootstrap': { args: [{ window_kind: 'minibar' | 'control_panel'; }]; result: { window_kind: 'minibar' | 'control_panel'; ui_status: 'ready' | 'recording' | 'processing' | 'inserted' | 'error'; trace_id: string; session_id?: string | null; runtime_mode: 'native_multi_window'; control_panel_url: string; } };
  'log_client_event': { args: [{ level: 'DEBUG' | 'INFO' | 'WARN' | 'ERROR'; trace_id: string; session_id?: string | null; module: string; event: string; message: string; error?: string | null; stack?: string | null; metadata_json?: string | null; }]; result: { accepted: boolean; } };
  'open_control_panel': { args: []; result: { opened: boolean; runtime_mode: 'native_multi_window'; } };
};

export type CommandArgs<T extends keyof CommandMap> = CommandMap[T]['args'];
export type CommandReturn<T extends keyof CommandMap> = CommandMap[T]['result'];
export type NativeInvokeFailure = { code: string; message: string; details?: string | null };
