// Generated by `zig build gen-types`. Do not edit manually.
export type CommandMap = {
  'ping': { args: [{ message: string; }]; result: { command: string; echoed: string; timestamp_ms: number; } };
  'sum': { args: [number, number]; result: { command: string; result: number; } };
  'echo': { args: [{ text: string; }]; result: { command: string; value: string; length: number; } };
  'health': { args: []; result: { command: string; ok: boolean; service: string; } };
  'multiplication': { args: [number, number]; result: { command: string; result: number; } };
  'soma': { args: [{ input_a: number; input_b: number; }]; result: { command: string; result: number; } };
  'multiply': { args: [{ left: number; right: number; }]; result: { command: string; result: number; } };
  'sub': { args: [number, number]; result: number };
  'getLastName': { args: [string]; result: string };
  'getFullName': { args: [string]; result: { text: string; } | { error: { message: string; }; } };
};

export type CommandArgs<T extends keyof CommandMap> = CommandMap[T]['args'];
export type CommandReturn<T extends keyof CommandMap> = CommandMap[T]['result'];
export type NativeInvokeFailure = { code: string; message: string; details?: string | null };
