// Generated by `zig build gen-types`. Do not edit manually.
import type { CommandMap, InvokeArgs, InvokeTuple } from './commands.generated';

declare global {
  interface Window {
    invoke(command: 'ping', args_0: { message: string; }): Promise<InvokeTuple<'ping'>>;
    invoke(command: 'sum', a: number, b: number): Promise<InvokeTuple<'sum'>>;
    invoke(command: 'echo', args_0: { text: string; }): Promise<InvokeTuple<'echo'>>;
    invoke(command: 'health'): Promise<InvokeTuple<'health'>>;
    invoke(command: 'multiplication', a: number, b: number): Promise<InvokeTuple<'multiplication'>>;
    invoke(command: 'soma', args_0: { input_a: number; input_b: number; }): Promise<InvokeTuple<'soma'>>;
    invoke(command: 'multiply', args_0: { left: number; right: number; }): Promise<InvokeTuple<'multiply'>>;
    invoke(command: 'sub', a: number, b: number): Promise<InvokeTuple<'sub'>>;
    invoke<T extends keyof CommandMap>(
      command: T,
      ...args: InvokeArgs<T>
    ): Promise<InvokeTuple<T>>;
  }
}

export {};
