// Generated by `zig build gen-types`. Do not edit manually.
export type CommandMap = {
  'ping': { request: { message: string; }; response: { command: string; echoed: string; timestamp_ms: number; } };
  'sum': { request: { a: number; b: number; }; response: { command: string; result: number; } };
  'echo': { request: { text: string; }; response: { command: string; value: string; length: number; } };
  'health': { request: Record<string, never>; response: { command: string; ok: boolean; service: string; } };
  'multiplication': { request: { first: number; second: number; }; response: { command: string; result: number; } };
};

export type InvokeRequest<T extends keyof CommandMap> = CommandMap[T]['request'];
export type InvokeResponse<T extends keyof CommandMap> = CommandMap[T]['response'];
