// Generated by `zig build gen-types`. Do not edit manually.
export type CommandMap = {
  'ping': { args: [{ message: string; }]; response: { command: string; echoed: string; timestamp_ms: number; } };
  'sum': { args: [number, number]; response: { command: string; result: number; } };
  'echo': { args: [{ text: string; }]; response: { command: string; value: string; length: number; } };
  'health': { args: []; response: { command: string; ok: boolean; service: string; } };
  'multiplication': { args: [number, number]; response: { command: string; result: number; } };
  'soma': { args: [{ input_a: number; input_b: number; }]; response: { command: string; result: number; } };
  'multiply': { args: [{ left: number; right: number; }]; response: { command: string; result: number; } };
  'sub': { args: [number, number]; response: number };
};

export type InvokeArgs<T extends keyof CommandMap> = CommandMap[T]['args'];
export type InvokeResponse<T extends keyof CommandMap> = CommandMap[T]['response'];
export type InvokeError = { code: string; message: string; details?: string | null };
export type InvokeTuple<T extends keyof CommandMap> = [InvokeResponse<T>, null] | [null, InvokeError];
