// Generated by `zig build gen-types`. Do not edit manually.
export type CommandMap = {
  'ping': { request: { message?: string }; response: { command: 'ping'; echoed: string; timestamp_ms: number } };
};

export type InvokeRequest<T extends keyof CommandMap> = CommandMap[T]['request'];
export type InvokeResponse<T extends keyof CommandMap> = CommandMap[T]['response'];
