// Generated by `zig build gen-types`. Do not edit manually.
import type { CommandMap } from './commands.generated';

export type InvokeResult<T extends keyof CommandMap> =
  | { ok: true; data: CommandMap[T]['response'] }
  | { ok: false; error: string; details?: string };

declare global {
  interface Window {
    invoke<T extends keyof CommandMap>(
      command: T,
      payload: CommandMap[T]['request']
    ): Promise<InvokeResult<T>>;
  }
}

export {};
