// Generated by `zig build gen-types`. Do not edit manually.
import type { CommandMap } from './commands.generated';

declare global {
  interface Window {
    invoke(name: string, payload?: unknown): Promise<unknown>;
    __mini: {
      invoke<T extends keyof CommandMap>(
        command: T,
        payload: CommandMap[T]['request']
      ): Promise<{ ok: true; data: CommandMap[T]['response'] } | { ok: false; error: string; details?: string }>;
    };
  }
}

export {};
