const std = @import("std");
const commands = @import("commands");

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const commands_path = "src/types-generated/commands.generated.d.ts";
    const global_path = "src/types-generated/global.generated.d.ts";
    const invoke_path = "src/lib/invoke.ts";

    var cmd_buf = std.array_list.Managed(u8).init(allocator);
    defer cmd_buf.deinit();
    const w = cmd_buf.writer();

    try w.writeAll("// Generated by `zig build gen-types`. Do not edit manually.\n");
    try w.writeAll("export type CommandMap = {\n");
    inline for (commands.specs) |spec| {
        try w.print("  '{s}': {{ args: ", .{spec.name});
        try writeTsType(w, spec.ArgsTuple);
        try w.writeAll("; response: ");
        try writeTsType(w, spec.Output);
        try w.writeAll(" };\n");
    }
    try w.writeAll("};\n\n");
    try w.writeAll("export type InvokeArgs<T extends keyof CommandMap> = CommandMap[T]['args'];\n");
    try w.writeAll("export type InvokeResponse<T extends keyof CommandMap> = CommandMap[T]['response'];\n");
    try w.writeAll("export type InvokeError = { code: string; message: string; details?: string | null };\n");
    try w.writeAll("export type InvokeTuple<T extends keyof CommandMap> = [InvokeResponse<T>, null] | [null, InvokeError];\n");
    try writeFile(commands_path, cmd_buf.items);

    var global_buf = std.array_list.Managed(u8).init(allocator);
    defer global_buf.deinit();
    const gw = global_buf.writer();
    try gw.writeAll("// Generated by `zig build gen-types`. Do not edit manually.\n");
    try gw.writeAll("import type { CommandMap, InvokeArgs, InvokeTuple } from './commands.generated';\n\n");
    try gw.writeAll("declare global {\n");
    try gw.writeAll("  interface Window {\n");
    try writeInvokeOverloads(gw);
    try gw.writeAll("    invoke<T extends keyof CommandMap>(\n");
    try gw.writeAll("      command: T,\n");
    try gw.writeAll("      ...args: InvokeArgs<T>\n");
    try gw.writeAll("    ): Promise<InvokeTuple<T>>;\n");
    try gw.writeAll("  }\n");
    try gw.writeAll("}\n\n");
    try gw.writeAll("export {};\n");
    try writeFile(global_path, global_buf.items);

    var invoke_buf = std.array_list.Managed(u8).init(allocator);
    defer invoke_buf.deinit();
    const iw = invoke_buf.writer();
    try iw.writeAll("// Generated by `zig build gen-types`. Do not edit manually.\n");
    try iw.writeAll("/// <reference path=\"../types-generated/global.generated.d.ts\" />\n\n");
    try iw.writeAll("import type {\n");
    try iw.writeAll("  CommandMap,\n");
    try iw.writeAll("  InvokeTuple,\n");
    try iw.writeAll("} from \"../types-generated/commands.generated\";\n\n");
    try iw.writeAll("export async function invoke<T extends keyof CommandMap>(\n");
    try iw.writeAll("  command: T,\n");
    try iw.writeAll("  ...args: CommandMap[T][\"args\"]\n");
    try iw.writeAll("): Promise<InvokeTuple<T>> {\n");
    try iw.writeAll("  return window.invoke(command, ...args);\n");
    try iw.writeAll("}\n");
    try writeFile(invoke_path, invoke_buf.items);
}

fn writeInvokeOverloads(gw: anytype) !void {
    inline for (commands.registry.registered_modules) |module| {
        const fields = @typeInfo(@TypeOf(module.commands)).@"struct".fields;
        inline for (fields) |field| {
            const fn_value = @field(module.commands, field.name);
            const fn_info = @typeInfo(@TypeOf(fn_value)).@"fn";

            try gw.print("    invoke(command: '{s}'", .{field.name});

            inline for (fn_info.params, 0..) |param, i| {
                const ParamT = param.type orelse @compileError("anytype parameters are not supported");
                const pname = resolveParamName(module, field.name, i);
                try gw.print(", {s}: ", .{pname});
                try writeTsType(gw, ParamT);
            }

            try gw.print("): Promise<InvokeTuple<'{s}'>>;\n", .{field.name});
        }
    }
}

fn resolveParamName(comptime module: type, comptime command_name: []const u8, comptime index: usize) []const u8 {
    if (@hasDecl(module, "command_meta")) {
        const meta = module.command_meta;
        if (@hasField(@TypeOf(meta), command_name)) {
            const cmd_meta = @field(meta, command_name);
            if (@hasField(@TypeOf(cmd_meta), "arg_names")) {
                const arg_names = cmd_meta.arg_names;
                const fields = @typeInfo(@TypeOf(arg_names)).@"struct".fields;
                if (index < fields.len) {
                    const idx_name = std.fmt.comptimePrint("{d}", .{index});
                    return @field(arg_names, idx_name);
                }
            }
        }
    }
    return std.fmt.comptimePrint("args_{d}", .{index});
}

fn writeTsType(w: anytype, comptime T: type) !void {
    if (isNumberType(T)) {
        try w.writeAll("number");
        return;
    }

    switch (@typeInfo(T)) {
        .bool => try w.writeAll("boolean"),
        .@"enum" => |e| {
            inline for (e.fields, 0..) |field, i| {
                if (i > 0) try w.writeAll(" | ");
                try w.print("'{s}'", .{field.name});
            }
        },
        .optional => |opt| {
            try writeTsType(w, opt.child);
            try w.writeAll(" | null");
        },
        .pointer => |ptr| {
            if ((ptr.size == .slice or ptr.size == .one) and ptr.child == u8) {
                try w.writeAll("string");
                return;
            }
            @panic("Unsupported pointer type for TS generation: " ++ @typeName(T));
        },
        .array => |arr| {
            try writeTsType(w, arr.child);
            try w.writeAll("[]");
        },
        .@"struct" => |s| {
            if (s.is_tuple) {
                try w.writeAll("[");
                inline for (s.fields, 0..) |field, i| {
                    if (i > 0) try w.writeAll(", ");
                    try writeTsType(w, field.type);
                }
                try w.writeAll("]");
                return;
            }

            if (s.fields.len == 0) {
                try w.writeAll("Record<string, never>");
                return;
            }

            try w.writeAll("{ ");
            inline for (s.fields, 0..) |field, i| {
                if (i > 0) try w.writeAll(" ");
                const is_optional = @typeInfo(field.type) == .optional;
                if (is_optional) {
                    try w.print("{s}?: ", .{field.name});
                } else {
                    try w.print("{s}: ", .{field.name});
                }
                try writeTsType(w, field.type);
                try w.writeAll(";");
            }
            try w.writeAll(" }");
        },
        .void => try w.writeAll("null"),
        else => @panic("Unsupported Zig type for TS generation: " ++ @typeName(T)),
    }
}

fn isNumberType(comptime T: type) bool {
    return T == i8 or T == i16 or T == i32 or T == i64 or T == i128 or
        T == isize or T == u8 or T == u16 or T == u32 or T == u64 or
        T == u128 or T == usize or T == c_short or T == c_ushort or
        T == c_int or T == c_uint or T == c_long or T == c_ulong or
        T == c_longlong or T == c_ulonglong or T == f16 or T == f32 or
        T == f64 or T == f80 or T == f128 or T == comptime_int or
        T == comptime_float;
}

fn writeFile(out_path: []const u8, content: []const u8) !void {
    if (std.fs.path.dirname(out_path)) |dir| {
        try std.fs.cwd().makePath(dir);
    }

    const file = try std.fs.cwd().createFile(out_path, .{ .truncate = true });
    defer file.close();
    try file.writeAll(content);
}
