const std = @import("std");
const commands = @import("commands");

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const commands_path = "web/types/commands.generated.d.ts";
    const global_path = "web/types/global.generated.d.ts";

    var buf = std.array_list.Managed(u8).init(allocator);
    defer buf.deinit();
    const w = buf.writer();

    try w.writeAll("// Generated by `zig build gen-types`. Do not edit manually.\n");
    try w.writeAll("export type CommandMap = {\n");
    inline for (commands.specs) |spec| {
        try w.print("  '{s}': {{ request: {s}; response: {s} }};\n", .{
            spec.name,
            spec.request_ts,
            spec.response_ts,
        });
    }
    try w.writeAll("};\n\n");
    try w.writeAll("export type InvokeRequest<T extends keyof CommandMap> = CommandMap[T]['request'];\n");
    try w.writeAll("export type InvokeResponse<T extends keyof CommandMap> = CommandMap[T]['response'];\n");

    try writeFile(commands_path, buf.items);

    var global_buf = std.array_list.Managed(u8).init(allocator);
    defer global_buf.deinit();
    const gw = global_buf.writer();
    try gw.writeAll("// Generated by `zig build gen-types`. Do not edit manually.\n");
    try gw.writeAll("import type { CommandMap } from './commands.generated';\n\n");
    try gw.writeAll("export type InvokeResult<T extends keyof CommandMap> =\n");
    try gw.writeAll("  | { ok: true; data: CommandMap[T]['response'] }\n");
    try gw.writeAll("  | { ok: false; error: string; details?: string };\n\n");
    try gw.writeAll("declare global {\n");
    try gw.writeAll("  interface Window {\n");
    try gw.writeAll("    invoke<T extends keyof CommandMap>(\n");
    try gw.writeAll("      command: T,\n");
    try gw.writeAll("      payload: CommandMap[T]['request']\n");
    try gw.writeAll("    ): Promise<InvokeResult<T>>;\n");
    try gw.writeAll("  }\n");
    try gw.writeAll("}\n\n");
    try gw.writeAll("export {};\n");

    try writeFile(global_path, global_buf.items);
}

fn writeFile(out_path: []const u8, content: []const u8) !void {
    if (std.fs.path.dirname(out_path)) |dir| {
        try std.fs.cwd().makePath(dir);
    }

    const file = try std.fs.cwd().createFile(out_path, .{ .truncate = true });
    defer file.close();
    try file.writeAll(content);
}
