const std = @import("std");
const commands = @import("commands");

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const commands_path = "web/types/commands.generated.d.ts";
    const global_path = "web/types/global.generated.d.ts";

    var buf = std.array_list.Managed(u8).init(allocator);
    defer buf.deinit();
    const w = buf.writer();

    try w.writeAll("// Generated by `zig build gen-types`. Do not edit manually.\n");
    try w.writeAll("export type CommandMap = {\n");
    inline for (commands.specs) |spec| {
        try w.print("  '{s}': {{ request: ", .{spec.name});
        try writeTsType(w, spec.Request);
        try w.writeAll("; response: ");
        try writeTsType(w, spec.Response);
        try w.writeAll(" };\n");
    }
    try w.writeAll("};\n\n");
    try w.writeAll("export type InvokeRequest<T extends keyof CommandMap> = CommandMap[T]['request'];\n");
    try w.writeAll("export type InvokeResponse<T extends keyof CommandMap> = CommandMap[T]['response'];\n");

    try writeFile(commands_path, buf.items);

    var global_buf = std.array_list.Managed(u8).init(allocator);
    defer global_buf.deinit();
    const gw = global_buf.writer();
    try gw.writeAll("// Generated by `zig build gen-types`. Do not edit manually.\n");
    try gw.writeAll("import type { CommandMap } from './commands.generated';\n\n");
    try gw.writeAll("export type InvokeResult<T extends keyof CommandMap> =\n");
    try gw.writeAll("  | { ok: true; data: CommandMap[T]['response'] }\n");
    try gw.writeAll("  | { ok: false; error: string; details?: string };\n\n");
    try gw.writeAll("declare global {\n");
    try gw.writeAll("  interface Window {\n");
    try gw.writeAll("    invoke<T extends keyof CommandMap>(\n");
    try gw.writeAll("      command: T,\n");
    try gw.writeAll("      payload: CommandMap[T]['request']\n");
    try gw.writeAll("    ): Promise<InvokeResult<T>>;\n");
    try gw.writeAll("  }\n");
    try gw.writeAll("}\n\n");
    try gw.writeAll("export {};\n");

    try writeFile(global_path, global_buf.items);
}

fn writeTsType(w: anytype, comptime T: type) !void {
    if (isNumberType(T)) {
        try w.writeAll("number");
        return;
    }

    const info = @typeInfo(T);
    switch (info) {
        .bool => try w.writeAll("boolean"),
        .@"enum" => |e| {
            inline for (e.fields, 0..) |field, i| {
                if (i > 0) try w.writeAll(" | ");
                try w.print("'{s}'", .{field.name});
            }
        },
        .optional => |opt| {
            try writeTsType(w, opt.child);
            try w.writeAll(" | null");
        },
        .pointer => |ptr| {
            if (ptr.size == .slice and ptr.child == u8) {
                try w.writeAll("string");
                return;
            }
            if (ptr.size == .one and ptr.child == u8) {
                try w.writeAll("string");
                return;
            }
            @panic("Unsupported pointer type for TS generation: " ++ @typeName(T));
        },
        .array => |arr| {
            if (arr.child == u8) {
                try w.writeAll("string");
                return;
            }
            try writeTsType(w, arr.child);
            try w.writeAll("[]");
        },
        .@"struct" => |s| {
            if (s.fields.len == 0) {
                try w.writeAll("Record<string, never>");
                return;
            }

            try w.writeAll("{ ");
            inline for (s.fields, 0..) |field, i| {
                if (i > 0) try w.writeAll(" ");
                const is_optional = @typeInfo(field.type) == .optional;
                if (is_optional) {
                    try w.print("{s}?: ", .{field.name});
                    try writeTsType(w, field.type);
                } else {
                    try w.print("{s}: ", .{field.name});
                    try writeTsType(w, field.type);
                }
                try w.writeAll(";");
            }
            try w.writeAll(" }");
        },
        .void => try w.writeAll("null"),
        else => @panic("Unsupported Zig type for TS generation: " ++ @typeName(T)),
    }
}

fn isNumberType(comptime T: type) bool {
    return T == i8 or T == i16 or T == i32 or T == i64 or T == i128 or
        T == isize or T == u8 or T == u16 or T == u32 or T == u64 or
        T == u128 or T == usize or T == c_short or T == c_ushort or
        T == c_int or T == c_uint or T == c_long or T == c_ulong or
        T == c_longlong or T == c_ulonglong or T == f16 or T == f32 or
        T == f64 or T == f80 or T == f128 or T == comptime_int or
        T == comptime_float;
}

fn writeFile(out_path: []const u8, content: []const u8) !void {
    if (std.fs.path.dirname(out_path)) |dir| {
        try std.fs.cwd().makePath(dir);
    }

    const file = try std.fs.cwd().createFile(out_path, .{ .truncate = true });
    defer file.close();
    try file.writeAll(content);
}
